terminos = [
    "sociedad", "cultura", "identidad", "rol", "norma", "clase social", "estatus", "conflicto", "comunidad", "interacción",
    "institución", "desigualdad", "ideología", "poder", "movilidad social", "globalización", "socialización", "etnocentrismo", "anomia", "marginalidad",
    "control social", "aculturación", "estructura social", "grupo social", "acción social", "roles sociales", "estratificación", "dinámica social",
    "agente socializador", "desviación", "enajenación", "fenómeno social", "proceso social", "identidad colectiva", "estigma", "multiculturalismo",
    "integración social", "alienación", "organización social", "conflicto social",
    "educación", "pedagogía", "aprendizaje", "enseñanza", "currículo", "evaluación", "didáctica", "alfabetización", "competencia", "metodología",
    "docencia", "motivación", "aula", "formación", "conocimiento", "instrucción", "aprendizaje significativo", "educación formal",
    "educación no formal", "educación inclusiva", "andragogía", "e-learning", "evaluación formativa", "evaluación sumativa", "constructivismo",
    "zona de desarrollo próximo", "aprendizaje autónomo", "enseñanza virtual", "ambiente de aprendizaje", "habilidades blandas", "competencias clave",
    "proceso de enseñanza", "mediación pedagógica", "neuroeducación", "metacognición", "educación emocional", "tutoría", "didáctica crítica",
    "educación personalizada", "enseñanza adaptativa",
    "psicología", "conducta", "emoción", "percepción", "cognición", "personalidad", "autoestima", "memoria", "atención", "desarrollo", "trauma",
    "inconsciente", "adaptación", "inteligencia emocional", "psicopatología", "trastorno", "resiliencia", "bienestar", "neurociencia",
    "psicología cognitiva", "refuerzo", "condicionamiento", "autoeficacia", "empatía", "neuroplasticidad", "atención plena", "trastorno de ansiedad",
    "trastorno depresivo", "trastorno bipolar", "esquizofrenia", "terapia cognitivo conductual", "conductismo", "humanismo", "psicoanálisis",
    "desarrollo cognitivo", "intervención psicológica", "regulación emocional", "creatividad",
    "estado", "democracia", "ciudadanía", "constitución", "ley", "derechos", "soberanía", "poder legislativo", "justicia", "participación",
    "representación", "gobernabilidad", "política pública", "derechos humanos", "sistema electoral", "partido político", "deliberación",
    "autoridad", "voto", "libertad", "estado de derecho", "sufragio", "sistema parlamentario", "poder ejecutivo", "poder judicial", "república",
    "dictadura", "monarquía", "libertad de expresión", "transparencia", "rendición de cuentas", "civismo", "consenso", "pluralismo",
    "representación proporcional", "voto obligatorio", "corrupción", "participación ciudadana", "derecho internacional", "jurisdicción",
    "ciencia", "método científico", "experimento", "hipótesis", "observación", "innovación", "tecnología", "informática", "dato", "sistema",
    "algoritmo", "inteligencia artificial", "cibernética", "simulación", "automatización", "red neuronal", "aprendizaje automático", "bioética",
    "análisis", "evidencia", "ingeniería", "tecnociencia", "biotecnología", "tecnología educativa", "sistema experto", "realidad aumentada",
    "realidad virtual", "robótica", "procesamiento de datos", "big data", "criptografía", "blockchain", "nube informática", "hardware",
    "software", "programación", "seguridad informática", "ética tecnológica", "tecnología sostenible", "computación cuántica",
    "comunicación", "lenguaje", "mensaje", "emisor", "receptor", "código", "canal", "contexto", "retroalimentación", "diálogo", "discurso",
    "narrativa", "oralidad", "semiótica", "signo", "texto", "interpretación", "lenguaje corporal", "alfabetización digital", "medios",
    "alfabetización mediática", "narrativa digital", "medios digitales", "influencia", "argumentación", "persuasión", "retórica",
    "comunicación interpersonal", "comunicación masiva", "periodismo", "noticia", "editorial", "publicidad", "propaganda", "infodemia",
    "comunicación institucional", "identidad cultural", "diversidad cultural", "cultura digital", "patrimonio cultural"
]
